name: Docker CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend
      run: docker build -t backend-test ./backend

    - name: Build Frontend
      run: docker build -t frontend-test ./frontend

    - name: Check Docker Compose Builds
      run: docker compose build

